config/routes.rb
Rails.application.routes.draw do
  
  # Home page
  root "lics#index"

  # Lic show pages
  get "listed-investment-companies/:id" => "lics#show", as: "listed_investment_company"

  # Dedicated summary pages
  get "share-price-vs-nta" => "share_price_vs_ntas#index"
  get "performance" => "performances#index"
  get "dividend-yields" => "dividend_yields#index"

  # Level 3 SEO Pages
  get "listed-investment-companies/:id/dividend-history" => "dividend_histories#show", as: "lics_dividend_histories"
  get "listed-investment-companies/:id/share-price-vs-nta" => "share_price_vs_ntas#show", as: "lics_share_price_vs_ntas"
  get "listed-investment-companies/:id/portfolio-holdings" => "portfolio_holdings#show", as: "lics_portfolio_holdings"
  get "listed-investment-companies/:id/performance" => "performances#show", as: "lics_performances"
  get "listed-investment-companies/:id/management-fees" => "expenses#show", as: "lics_expenses"
  get "listed-investment-companies/:id/annual-reports" => "annual_reports#show", as: "lics_annual_reports"
  
  # Redirects
  get '/listed-investment-companies', to: redirect('/')   # This was an only page, no longer in use. 

end

app/views/shared/_chart_cost_indicator_excluding_performance_fees.html.erb
<div class="chart-style-template">
    <%= column_chart @lic.chart_cost_indicator_excluding_performance_fees, **cost_indicator_total_chart_styling %>
</div>

app/views/shared/_chart_cost_indicator_form.html.erb
<%= form_tag listed_investment_company_path(id: @lic.slug), method: :get, data: { turbo_frame: "cost_indicator" }, id: "chart-filter-options" do %>

    <div class="chart-filter-option">
        <label for="cost_indicator_view" class="chart-filter-label">Cost Indicator View:</label>
        <%= select_tag "cost_indicator_view", options_for_select([
            ["Excluding Performance Fees", "excluding_performance_fees"],
            ["Including Performance Fees", "total"],
            ["Show Cost Indicator Types", "split"],
            ],
            selected: "excluding_performance_fees"
            ), 
            class: "chart-filter-select",
            data: { turbo_frame: "cost_indicator" }
        %>
    </div>

    <%= button_tag "Update Chart", class: "chart-button", data: { turbo_frame: "cost_indicator" } %>
<% end %>

app/views/shared/_chart_cost_indicator_split.html.erb
<div class="chart-style-template">
    <%= column_chart @lic.chart_cost_indicator_split, stacked: true, **cost_indicator_split_chart_styling %>
</div>

app/views/shared/_chart_cost_indicator_total.html.erb
<div class="chart-style-template">
    <%= column_chart @lic.chart_cost_indicator_total, **cost_indicator_total_chart_styling %>
</div>

app/views/shared/_chart_costs_incurred_form.html.erb
<%= form_tag listed_investment_company_path(id: @lic.slug), method: :get, data: { turbo_frame: "costs_incurred" }, id: "chart-filter-options" do %>
    
    <div class="chart-filter-option">
        <label for="costs_incurred_view" class="chart-filter-label">Actual Costs View:</label>
        <%= select_tag "costs_incurred_view", options_for_select([
            ["Total Costs", "total"],
            ["Show Cost Types", "split"],
            ],
            selected: "total"
            ), 
            class: "chart-filter-select",
            data: { turbo_frame: "costs_incurred" }
        %>
    </div>

    <%= button_tag "Update Chart", class: "chart-button", data: { turbo_frame: "costs_incurred" } %>
<% end %>

app/views/shared/_chart_costs_incurred_split.html.erb
<div class="chart-style-template">
    <%= column_chart @lic.chart_costs_incurred_split, stacked: true, **costs_incurred_split_chart_styling %>
</div>

app/views/shared/_chart_dividend_history_annualised.html.erb
<div class="chart-style-template">
    <%= column_chart @lic.chart_dividend_history_annualised, **dividend_history_annualised_chart_styling %>
</div>

app/views/shared/_chart_dividend_history_form.html.erb
<%= form_tag listed_investment_company_path(id: @lic.slug), method: :get, data: { turbo_frame: "dividend_history" }, id: "chart-filter-options" do %>

    <div class="chart-filter-option">
        <label for="dividend_history_view" class="chart-filter-label">Dividend History View:</label>
        <%= select_tag "dividend_history_view", options_for_select([
            ["Total Annual Cash Dividends", "annualised"],
            ["Total including Franking Credits", "franking"],
            ["Show Dividend Types", "split"]
            ],
            selected: "annualised"
            ), 
            class: "chart-filter-select",
            data: { turbo_frame: "dividend_history" }
        %>
    </div>
    
    <%= button_tag "Update Chart", class: "chart-button", data: { turbo_frame: "dividend_history" } %>
<% end %>

app/views/shared/_chart_dividend_history_franking.html.erb
<div class="chart-style-template">
    <%= column_chart @lic.chart_dividend_history_franking, stacked: true, **dividend_history_franking_chart_styling %>
</div>

app/views/shared/_chart_share_price_vs_nta.html.erb
<div class="chart-share-price-vs-nta-filter">

  <%= form_tag(url_for(action: 'show', id: @lic.slug), method: "get", id: "chart-filter-options") do %>

    <!-- Tax Type Selection -->
    <div class="chart-filter-option">
      <label for="tax_type" class="chart-filter-label">NTA Tax Type:</label>
      <%= select_tag 'tax_type', options_for_select([['Pre Tax', 'pre_tax'], ['Post Tax', 'post_tax']], @selected_tax_type), class: "chart-filter-select" %>
    </div>

    <!-- Time Duration Selection -->
    <div class="chart-filter-option">
      <label for="time_duration" class="chart-filter-label">Time Duration:</label>
      <%= select_tag 'time_duration', options_for_select((1..10).map { |i| [ "#{i} Year#{'s' if i > 1}", i ] }, @selected_time_duration), class: "chart-filter-select" %>
    </div>

    <!-- Update Chart Button -->
    <%= submit_tag "Update Chart", class: "chart-button" %>

  <% end %>

</div>


<!-- SP vs NTA Chart -->
<div class="chart-style-template chart-share-price-vs-nta">
  <%= column_chart lic.chart_share_price_vs_nta(@selected_time_duration, @selected_tax_type), 
      suffix: "%", 
      round: 1,
      **share_price_vs_nta_chart_styling(@selected_time_duration, @selected_tax_type, lic) 
  %>
</div>

app/views/shared/_dividend_payments_table.html.erb
<table class="dividend-payments-table">
    <thead>
        <tr>
            <th>Payment Date</th>
            <th>Dividend Type</th>
            <th>Dividend Amount</th>
            <th>Franking Level</th>
        </tr>
    </thead>
    <tbody>
        <% div_payments.each do |div| %>
            <tr>
                <td><%= div.payment_date.strftime("%d %b, %Y") %></td>
                <td><%= div.dividend_phase %></td>
                <td><%= dividend_amounts_formatted(div.cash_amount)%></td>
                <td><%= (div.franking_level * 100).round %>%</td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/shared/_dividend_payments_table_full.html.erb
<%= render partial: 'shared/dividend_payments_table', locals: { div_payments: @dividend_payments_full } %>

<% if current_page?(lics_dividend_histories_path(lic, dividend_payments_view_type: "full")) %>
    <%= link_to "Show fewer rows", 
        lics_dividend_histories_path(lic, dividend_payments_view_type: "limited"), 
        data: { turbo_frame: "dividend_payments" }, 
        class: "dividend-payments-table-size-link" 
    %>
<% else %>
    <%= link_to "Show fewer rows", 
        listed_investment_company_path(lic, dividend_payments_view_type: "limited"), 
        data: { turbo_frame: "dividend_payments" }, 
        class: "dividend-payments-table-size-link" 
    %>
<% end %>

app/views/shared/_portfolio_holdings_table.html.erb
<!-- Portfolio Holdings Section Sub-Heading -->
<h3>
    <% if lic.portfolio_holdings_ordering_style(@portfolio_holdings_display_year) == "Weight" %>
        Top <%= lic.portfolio_holdings(@portfolio_holdings_display_year).size %> Holdings at end of FY <%= lic.portfolio_holdings(@portfolio_holdings_display_year).first.year %>
    <% else %>
        Sample of Top Holdings at end of FY <%= lic.portfolio_holdings(@portfolio_holdings_display_year).first.year %> (Alphabetical Order)
    <% end %>
</h3>

<!-- Table Filter -->
<div class="chart-share-price-vs-nta-filter">
    <%= form_tag(url_for(action: 'show', id: @lic.slug), method: "get", id: "chart-filter-options") do %>
        <div class="chart-filter-option">
            <label for="portfolio_holdings_display_year" class="chart-filter-label">Year:</label>
            <%= select_tag 'portfolio_holdings_display_year',
                options_for_select(@portfolio_holdings_display_year_options.each { |year| [year, year] }, @portfolio_holdings_display_year),
                class: "chart-filter-select"
            %>
        </div>
        <%= submit_tag "Update Table", class: "chart-button" %>
    <% end %>
</div>

<!-- Portfolio Holdings Table -->
<div class="portfolio-holdings-table-container ll-scrollbar">
    <table class="portfolio-holdings-table">
        <thead>
            <tr>
                <th></th>
                <th>Holding</th>
                <% if lic.portfolio_holdings_ordering_style(@portfolio_holdings_display_year) == "Weight" %>
                    <th style="text-align: center;">Weight</th>
                <% end %>
                <th>Sector</th>
                <% if @device_type == 'desktop' %>
                    <th>Industry</th>
                    <th>Size</th>
                    <th>HQ</th>
                <% end %>
            <tr>
        </thead>
        <tbody>
            <% lic.portfolio_holdings(@portfolio_holdings_display_year).each_with_index do |holding, i| %>
                <tr>
                    <td><%= i+1 %></td>
                    <td>
                        <% if @device_type == 'mobile' %>
                            <%= truncate(holding.holding_name, length: 25, omission: '') %>
                        <% else %>
                            <%= truncate(holding.holding_name, length: 32, omission: '') %>
                        <% end %>
                    </td>
                    <% if lic.portfolio_holdings_ordering_style(@portfolio_holdings_display_year) == "Weight" %>
                        <td style="text-align: center;"><%= holding.weight%>%</td>
                    <% end %>
                    <td><%= holding.sector %></td>
                    <% if @device_type == 'desktop' %>
                        <td><%= truncate(holding.industry, length: 30, omission: '') %></td>
                        <td><%= holding.size %></td>
                        <td><%= holding.headquartered %></td>
                    <% end %>
                </tr>
            <% end %>
            <% if lic.portfolio_holdings_cash(@portfolio_holdings_display_year) && lic.portfolio_holdings_ordering_style(@portfolio_holdings_display_year) == "Weight" %>
                <tr>
                    <td>-</td>
                    <td>Cash & Cash Equivalents</td>
                    <td style="text-align: center;"><%= lic.portfolio_holdings_cash(@portfolio_holdings_display_year) %>%</td>
                    <td>-</td>
                    <% if @device_type == 'desktop' %>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
        

app/views/shared/_show_page_separator.html.erb
<!-- Section Separator on Lic Show Page-->

<div class="show-page-section-separator">
  ~ <%= @lic.name %> (<%= @lic.ticker %>) ~
</div>