config/routes.rb
Rails.application.routes.draw do
  
  # Home page
  root "lics#index"

  # Lic show pages
  get "listed-investment-companies/:id" => "lics#show", as: "listed_investment_company"

  # Dedicated summary pages
  get "share-price-vs-nta" => "share_price_vs_ntas#index"
  get "performance" => "performances#index"
  get "dividend-yields" => "dividend_yields#index"

  # Level 3 SEO Pages
  get "listed-investment-companies/:id/dividend-history" => "dividend_histories#show", as: "lics_dividend_histories"
  get "listed-investment-companies/:id/share-price-vs-nta" => "share_price_vs_ntas#show", as: "lics_share_price_vs_ntas"
  get "listed-investment-companies/:id/portfolio-holdings" => "portfolio_holdings#show", as: "lics_portfolio_holdings"
  get "listed-investment-companies/:id/performance" => "performances#show", as: "lics_performances"
  get "listed-investment-companies/:id/management-fees" => "expenses#show", as: "lics_expenses"
  get "listed-investment-companies/:id/annual-reports" => "annual_reports#show", as: "lics_annual_reports"
  
  # Redirects
  get '/listed-investment-companies', to: redirect('/')   # This was an only page, no longer in use. 

end

app/models/portfolio_holding.rb
class PortfolioHolding < ApplicationRecord
    belongs_to :lic
end

app/controllers/portfolio_holdings_controller.rb
class PortfolioHoldingsController < ApplicationController

    def show
        @lic = Lic.find_by!(slug: params[:id])

        # Portfolio Holdings Table
        @portfolio_holdings_display_year_options = @lic.portfolio_holdings_unique_years
        @portfolio_holdings_latest_year = @lic.portfolio_holdings_latest_year
        @portfolio_holdings_display_year = params[:portfolio_holdings_display_year].presence&.to_i || @portfolio_holdings_latest_year
        @portfolio_holdings_table_data = @lic.portfolio_holdings(@portfolio_holdings_display_year)

        respond_to do |format|
            format.html
            format.turbo_stream do
                if params[:portfolio_holdings_display_year]
                    render turbo_stream: turbo_stream.update("portfolio_holdings") do
                        render partial: "shared/portfolio_holdings_table", locals: { lic: @lic, portfolio_holdings_display_year: @portfolio_holdings_display_year }
                    end
                end
            end
        end
    end

end

app/helpers/portfolio_holdings_helper.rb
module PortfolioHoldingsHelper
end

app/views/portfolio_holdings/_show_page_seo_text.html.erb
<div class="seo-pages-seo-text-section" data-controller="seo-pages-seo-text">
    <div class="seo-pages-seo-text-container">
        <h2 class="seo-pages-seo-text-header">FAQ’s about <%= @lic.ticker %>’ Portfolio Holdings</h2>

        <div class="seo-pages-seo-text-columns">

            <!-- Left Column Questions -->   
            <div class="seo-pages-seo-text-left-column">
                <div class="seo-pages-seo-text-item">
                    <button class="seo-pages-seo-text-question" data-action="seo-pages-seo-text#toggle" data-seo-pages-seo-text-target="question">
                        Where can I find <%= @lic.ticker %>’s Portfolio Holdings?
                        <span class="seo-pages-seo-text-toggle-icon"> +</span>
                    </button>
                    <div class="seo-pages-seo-text-answer" data-seo-pages-seo-text-target="answer">
                        <p>When researching the Portfolio Holdings for a Listed Investment Company, such as <%= @lic.name %>, the two go-to places to find this information include:</p>
                            <ul>
                                <li>Monthly updates to the ASX</li>
                                <li>Annual Reports</li>
                            </ul>
                        <p>The majority of Listed Investment Companies will provide a snapshot of their holdings (e.g. top 10 or top 20 holdings) in their monthly updates. However, some choose not to (usually the more ‘active’ managers), most likely because they view this information as their valuable IP.</p>
                        <p>If the portfolio holdings aren’t shared in the monthly updates, then it’s likely this information will be shared in historical annual reports (<%= link_to "link here", lics_annual_reports_path, target: :_blank %> for these reports for <%= @lic.name %>). It can be an interesting research exercise to view the change in the Portfolio Holdings over time (e.g. the last 5 or 10 years) to get a feel on how active the manager is (i.e. are the holdings changing a lot from year to year), and whether they were early in identifying successful investments that most LICs now own (CSL as an example). </p>
                    </div>
                </div>
             </div>

            <!-- Right Column Questions -->   
            <div class="seo-pages-seo-text-right-column">
                <div class="seo-pages-seo-text-item">
                    <button class="seo-pages-seo-text-question" data-action="seo-pages-seo-text#toggle" data-seo-pages-seo-text-target="question">
                        Why is researching <%= @lic.ticker %>’s Portfolio Holdings important?
                        <span class="seo-pages-seo-text-toggle-icon"> +</span>
                    </button>
                    <div class="seo-pages-seo-text-answer" data-seo-pages-seo-text-target="answer">
                        <p>When investing in a Listed Investment Company, such as <%= @lic.name %>, that LIC itself isn’t operating (i.e. it’s not producing products or services, or has sales and profits). The LICs responsibility is to manage your investment by itself investing into actual operating companies, such as BHP or CBA. Therefore, when researching a LIC, it makes sense to research and understand, and then feel comfortable and confident, with the underlying portfolio holdings, as this is what you are indirectly investing into, when making an investment in the LIC.</p>
                        <p>Questions to think about when researching the portfolio holdings include:</p>
                            <ul>
                                <li><u>What types of companies or assets does the LIC invest in?:</u> Are they large-cap or small-cap, mature companies or growth companies, older industrial style companies or new-age tech? This will be a personal preference for the investor on the types of investment they prefer to own long-term.</li>
                                <li><u>What geographies does the LIC invest in?:</u> Are they mainly Australian companies, or does the LIC focus globally? Some LICs also focus on a specific global region, such as Asia.</li>
                                <li><u>How concentrated are the portfolio holdings?:</u> Some LICs are invested in up to 100 holdings, and as a result, the position size of the top 10 positions are in the low single digit percentages. Conversely, some LICs are consented into 15 to 30 holdings, and therefore position sizes of the top holdings are 10% or higher. There’s no right or wrong to this question, it’s a personal preference of risk tolerance and view on concentration vs diversification.</li>
                            </ul>
                    </div>
                </div>
             </div>

        </div>
    </div>
</div>

app/views/portfolio_holdings/show.html.erb
<!-- SEO details -->
<% content_for :title do %>
  Portfolio Holdings | <%= @lic.name %> (ASX:<%= @lic.ticker %>)
<% end %>

<% content_for :description do %>
  [<%= Time.now.strftime("%b %Y") %> Updated] Current and Historical Portfolio Holdings for <%= @lic.name %> (ASX: <%= @lic.ticker %>). See Top 20 Holdings, plus Cash weighting.
<% end %>

<% content_for :keywords do %>
  <%= @lic.name %>, <%= @lic.ticker %>, Portfolio Holdings
<% end %>

<!-- Back to Lic Show Page Button -->
<%= render partial: "shared/l3_seo_page_back_button" %>

<!-- Page Header -->
<div class="seo-pages-header">
  <h1><%= @lic.ticker %> - Portfolio Holdings</h1>
</div>
<div class="seo-pages-page-details">
  <p>Portfolio Holdings information for <%= @lic.name %> (ASX: <%= @lic.ticker %>)</p>
</div>

<!-- Portfolio Holdings Table -->
<%= turbo_frame_tag "portfolio_holdings" do %>
  <%= render partial: 'shared/portfolio_holdings_table', locals: { lic: @lic, portfolio_holdings_display_year: @portfolio_holdings_display_year } %>
<% end %>

<!-- Back to Lic Show Page Section -->
<%= render partial: 'shared/l3_seo_page_back_section' %>

<!-- SEO Text Section -->
<%= render partial: 'portfolio_holdings/show_page_seo_text' %>