config/routes.rb
Rails.application.routes.draw do
  
  # Home page
  root "lics#index"

  # Lic show pages
  get "listed-investment-companies/:id" => "lics#show", as: "listed_investment_company"

  # Dedicated summary pages
  get "share-price-vs-nta" => "share_price_vs_ntas#index"
  get "performance" => "performances#index"
  get "dividend-yields" => "dividend_yields#index"

  # Level 3 SEO Pages
  get "listed-investment-companies/:id/dividend-history" => "dividend_histories#show", as: "lics_dividend_histories"
  get "listed-investment-companies/:id/share-price-vs-nta" => "share_price_vs_ntas#show", as: "lics_share_price_vs_ntas"
  get "listed-investment-companies/:id/portfolio-holdings" => "portfolio_holdings#show", as: "lics_portfolio_holdings"
  get "listed-investment-companies/:id/performance" => "performances#show", as: "lics_performances"
  get "listed-investment-companies/:id/management-fees" => "expenses#show", as: "lics_expenses"
  get "listed-investment-companies/:id/annual-reports" => "annual_reports#show", as: "lics_annual_reports"
  
  # Redirects
  get '/listed-investment-companies', to: redirect('/')   # This was an only page, no longer in use. 

end

app/views/layouts/_back_to_top_button.html.erb
<button id="back-to-top-button">↑</button>

<script>
    //Get the button
    var mybutton = document.getElementById("back-to-top-button");

    // When the user scrolls down 300px from the top of the document, show the button
    window.onscroll = function() {
    scrollFunction();
    };

    function scrollFunction() {
    if (document.body.scrollTop > 500 || document.documentElement.scrollTop > 500) {
        mybutton.style.display = "block";
    } else {
        mybutton.style.display = "none";
    }
    }

    // When the user clicks on the button, scroll to the top of the document
    mybutton.addEventListener("click", function() {
    window.scrollTo({ top: 0, behavior: "smooth" });
    });

</script>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <div class="footer-container">

    <span class="footer-item">&copy; Listed Landscape <%= Time.current.year %></span>
    
    <span class="footer-item footer-hide-mobile">|</span>
    
    <span class="footer-item">hello@listedlandscape.com</span>

  </div>
  
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container header-container">
    
    <!-- Logo -->
    <div class="logo">
      <%= link_to image_tag('/listed_landscape_header_logo_350x50px.png', alt: 'Listed Landscape Website Logo'), root_path %>
    </div>


    <!-- Menu -->
    <div data-controller="mobile-menu">
      <!-- Mobil menu -->
      <div id="mobile_menu" class="mobile_menu" data-action="click->mobile-menu#toggle">
        <div class="mobile_menu_line"></div>
        <div class="mobile_menu_line"></div>
        <div class="mobile_menu_line"></div>
      </div>
      <!-- Menu links -->
      <div id="menu-items" class="menu-items" data-mobile-menu-target="menu">
        <%= link_to 'NTAs', share_price_vs_nta_path, class: 'menu-link' %>
        <%= link_to 'Performance', performance_path, class: 'menu-link' %>
        <%= link_to 'Dividends', dividend_yields_path, class: 'menu-link' %>
        <%= link_to 'Home', root_path, class: 'menu-link' %>
      </div>
    </div>
  
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <html lang="en">
    
    <title><%= (yield(:title).presence || "Listed Landscape | Australian LICs").strip %></title>
    <meta name="description" content="<%= (yield(:description).presence || "[#{Time.now.strftime('%b %Y')}] Exploring Australian Listed Investment Companies (LICs). Performance, Portfolio Holdings, Dividend History, Profit Reserves, Fees ..").strip %>">
    <meta name="keywords" content="<%= (yield(:keywords).presence || 'Listed Landscape, Listed Investment Companies, LICs').strip %>">
    <link rel="icon" type="image/png" sizes="48x48" href="/listed_landscape_favicon_48x48px.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/listed_landscape_app_touch_icon_180x180px.png">

    <meta property="og:title" content="Listed Landscape">
    <meta property="og:description" content="Exploring Australian Listed Investment Companies (LICs)">
    <meta property="og:image" content="/listed_landscape_preview_1200x630px.png">
    <meta property="og:url" content="https://listedlandscape.com">

    <link rel="canonical" href="<%= canonical_url %>">    

    <!-- JSON-LD Org Markup -->
    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "Listed Landscape",
        "legalName": "Listed Landscape Pty Ltd",
        "url": "https://listedlandscape.com",
        "logo": "/listed_landscape_header_logo_400x50px.png",
        "foundingDate": "2023",
        "founders": [
          {
            "@type": "Person",
            "name": "John Fox"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "addressLocality": "Gold Coast",
          "addressCountry": "Australia"
        },
        "contactPoint": {
          "@type": "ContactPoint",
          "contactType": "customer support",
          "email": "support@listedlandscape.com"
        },
        "sameAs": [
          "https://twitter.com/listedlandscape"
        ]
      }
    </script>

    <!-- Google Analytics -->
    <% if Rails.env.production? %>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-LX73RJ82VC"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-LX73RJ82VC');
      </script>
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex-container">
      <%= render "layouts/header" %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>